### PR TITLE
add new OCs

### PR DESCRIPTION
**Pull request by LordFoogThe4rd**

### CODE REVIEW

**Comment by kagrith** [comment]
Hiya, just wanted to chime in here.
I downloaded this and shoved it into the build.
I got the following error (sanitized)

```
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2074 column 5 (char 53715)
```

Sure enough, end of line on 2073 is missing a comma delimiter, just like line 2059 for reference.

Which led to error:
`json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2243 column 1 (char 58143)`

This was less clear to me.
2243 appears to be the end of the file, after pruning some whitespace,
It occured to me that there appeared to be an unnecessary comma on line 2241.
Being that JSON is a comma delimited format, the last item in a list should not have a trailing comma.

Sure enough, after making those changes, running main.py opened the editor right up.
I brought a save file in, and set the overclocks to unacquired, and sure enough, they populated properly.

I noticed that the M1000 Classic, DeepCore GK2, and Thunderhead appeared to not show my existing overclocks as forged.
I added them to be cautious.

The seasonal section appears to need some work still.
I've backed up my saves just in case, but ill be saving and testing the file anyway, just to see if keeping the values the same does allow for easy acquisition of the new overclocks.

**Comment by kagrith** [comment]
> but all other overclocks show properly? I saw that the GUIDs in the game file was different so I thought I had to update that too, seems like I need to rollback

Seems to do, yes.
Just the ones referenced appeared to be mismatched for some reason. T'was the whole category by the look of it.

**Comment by AnthonyMichaelTDM** [comment]
Hey, thanks for doing this. When this PR is ready, and someone else can confirm it’s working, ping me specifically and I’ll get it merged.

**Comment by AnthonyMichaelTDM** [comment]
I got them from save files

**Comment by AnthonyMichaelTDM** [comment]
Yes, exactly, I forgot the exact one I used i think it was like “hex3d” or something idk, it was a windows app so I can’t use it anymore bc I use Linux now

**Comment by AnthonyMichaelTDM** [comment]
Pretty much, it’s kind of a pain in the ass

**Comment by kagrith** [comment]
> @kagrith can you test this change?

Tried the new guids file.
No errors when saving, however, when loading up the game, none of the new overclocks showed up.
Adjusted a level to check if the safe file was being read by the game properly, and sure enough, new levels showed up, but the OCs remain outside of forge.

**Comment by BlitWizbok** [comment]
Can confirm @kagrith agrith's findings. OC's are in the editor, and there's no errors when saving, but they're absent from the forge.

**Comment by AnthonyMichaelTDM** [comment]
I think it's just overclocks, but don't cite me on that.

**Comment by Ecksters** [comment]
@LordFoogThe4rd https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/issues/61#issuecomment-2185256782

**Comment by wahlp** [comment]
looking through the changes, i think the GUIDs updated might be wrong.

based on my own testing, the reworked stubby overclock's GUID has stayed the same since the update and does not actually need changing.

all the other changed GUIDs might also be incorrect. this would explain how there are no errors when saving, but the overclocks don't appear.

---

@LordFoogThe4rd i'm willing to hunt down the correct GUIDs if you need help

**Comment by xXramzS** [comment]
Please do let me know if there is anything i can do. if it's a matter of trial and error i mean, and you need help dividing the task, i could wholeheartedly help.

**Comment by wahlp** [comment]
using that save with all the OCs, i made a save with the 12 new OCs waiting to be forged.
there may be a 1 or 2 additional GUIDs under OwnedSchematics that don't appear ingame, which i think means they're not valid.
[season5-ocs-unforged.zip](https://github.com/user-attachments/files/16117420/season5-ocs-unforged.zip)

by forging them one by one, i've identified which GUID belongs to which OC.
this is what it looks like now.
[guids.json](https://github.com/user-attachments/files/16117390/guids.json)

anyone can try replacing the current `guids.json` with that and see if it works.

**Comment by kagrith** [comment]
I'll give this a try shortly.
Will advise.

**Comment by xXramzS** [comment]
Haven't tried all OCs, but Mortar Rounds, Pump Action and Rotary Overdrive work.

**Comment by xXramzS** [comment]
okay i've tried almost all of them, it seems to work.
i think let someone else try too, but it seems fine

**Comment by kagrith** [comment]
Can confirm all 12 overclocks were forge-able after plugging in this guids.

> using that save with all the OCs, i made a save with the 12 new OCs waiting to be forged. there may be a 1 or 2 additional GUIDs under OwnedSchematics that don't appear ingame, which i think means they're not valid. [season5-ocs-unforged.zip](https://github.com/user-attachments/files/16117420/season5-ocs-unforged.zip)
> 
> by forging them one by one, i've identified which GUID belongs to which OC. this is what it looks like now. [guids.json](https://github.com/user-attachments/files/16117390/guids.json)
> 
> anyone can try replacing the current `guids.json` with that and see if it works.

**Review by AnthonyMichaelTDM — APPROVED** [review]
Sweet, thanks for the work everyone

**Pull request merged**
