### PR TITLE
fix: builds not building

### PR DESCRIPTION
**Pull request by wahlp**

### CODE REVIEW

**Comment by wahlp** [comment]
works on my fork: https://github.com/wahlp/DRG-Save-Editor/releases/tag/v1.9.1

**Comment by AnthonyMichaelTDM** [comment]
yeah, I noticed, should be fixed in a few minutes

**Comment by AnthonyMichaelTDM** [comment]
this run *would* have worked, https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/actions/runs/9886761578/job/27307150559

going to remove the workflow_dispatch derective and recreate the tags to trigger a new release

**Comment by AnthonyMichaelTDM** [comment]
if [this](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/actions/runs/9886807912) successfully builds a release, I'm going to close this

**Comment by AnthonyMichaelTDM** [comment]
builds build now, the archive for linux is a bit funky though so I'm going to fix that first

**Comment by AnthonyMichaelTDM** [comment]
instead of recreating the release, I just uploaded the fixed artifact, going to close this now. Thanks again

**Pull request closed without merging**
