### PR TITLE
Refactor components further

### PR DESCRIPTION
**Pull request by wahlp**
#75 

goals: 
- break down the main file into something that looks more like MVC
- the last PR left the state manager reliant on class variables. change it to use instance variables to make it more testable in future

### CODE REVIEW

**Review by simon-wg — COMMENTED** [review]
This looks really nice, great job! 

I'll just have to take a closer look at it and run it once I get home from work before I approve.

**Comment by wahlp** [comment]
certainly not a perfect separation of responsibilities between the controller and view, but it feels great to see how much smaller each file is compared to the original `main.py`

**Comment by simon-wg** [comment]
I took this opportunity to convert Item and Cost to dataclasses as well, and also added a __add__ to Cost so we don't have to iterate over each key.

But it works well on my machine! Great job again :D

**Comment by AnthonyMichaelTDM** [comment]
ping me when this is ready to review/merge

**Comment by wahlp** [comment]
@AnthonyMichaelTDM it's ready

**Comment by AnthonyMichaelTDM** [comment]
sweet, I'll take a look

**Review by AnthonyMichaelTDM — APPROVED** [review]
looks good to me, thanks for the work

**Pull request merged**
