### PR TITLE
Update for season 5

### LINKED ISSUE #61: update for season 5
Season 5 came out so this needs updated

### PR DESCRIPTION
**Pull request by wahlp**
fixes #61

### CODE REVIEW

**Comment by AnthonyMichaelTDM** [comment]
If someone can confirm this works, I'll merge asap

**Comment by wahlp** [comment]
https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/issues/61#issuecomment-2185256782

tested against this save as well as my own, but somebody else confirming would be nice.

**Comment by meanliar** [comment]
Out of curiosity, why are season_xp_offset and scrip_offset defined in two separate places? wouldn't it be better practice to have them defined in one place and referenced?

**Comment by xXramzS** [comment]
What i did:
- Set everything up (updating the editor, setting up venv, etc)
- wanted to remove rocket barrage but couldn't seem to be able to, added plasma burster missiles which showed as unforged even though i didn't have it earlier
- added fatboy
- fatboy now does appear as unforged, but plasma burster missiles is nowhere to be found

**Comment by xXramzS** [comment]
hurricane's plasma burster missiles appear as "forged" but are nowhere to be seen

**Comment by xXramzS** [comment]
there also are missing OCs, but i would assume that this is handled by another pull request

**Comment by xXramzS** [comment]
plasma burster missiles appears in forge history but not in the overclock menu on the weapon. weird.

**Comment by wahlp** [comment]
yes, the changes only touch on the seasonal currency and progression

**Comment by xXramzS** [comment]
oh my bad, can confirm that it works in that regard

**Comment by AnthonyMichaelTDM** [comment]
Sweet, thanks, merging

**Comment by wahlp** [comment]
also fixed #61

**Comment by bbeenn1** [comment]
If it helps, the following issues are part of Weapon Experience being added (so offsets) or Season 5 (new GUID)
https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/issues/42 https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/issues/48 https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/issues/49 https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/issues/52 https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/issues/55 https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/issues/56

**Comment by alexskirata** [comment]
Could you also add support for previous seasons? Now we can choose what season we want to play and I checked - the editor can add seasonal progress only for season 5.

**Comment by AnthonyMichaelTDM** [comment]
That’s shouldn’t be too hard, a simple drop-down should suffice

**Pull request merged**
