### PR TITLE
Updated definitions for season 4

### PR DESCRIPTION
**Pull request by Its-Casino**
Added the GUID for the new season and changed the definition so it uses it.

Tested edit season level on my machine, which worked.

### CODE REVIEW

**Comment by AnthonyMichaelTDM** [comment]
Awesome, thank you

**Comment by AnthonyMichaelTDM** [comment]
I'll put together a release later, if I find time

**Comment by LoneStrider18** [comment]
So how do you get this with the season 4 update, or is that what is being waited on? I'm just a little confused because I got here from an issues page saying the season 4 update of the save editor was located here. If this can be clarified, I thank you for doing so.

**Comment by Its-Casino** [comment]
It's already merged, just follow the installation steps and it should work for s4

**Comment by LoneStrider18** [comment]
> It's already merged, just follow the installation steps and it should work for s4

OK, thank you. Another question though. Does this also support unlocking cosmetics, specifically ones that you can't get anymore? None of the ones available for purchase right now.

**Comment by AnthonyMichaelTDM** [comment]
No, that's a long-term "would be nice" feature that isn't actively being developed.

the difficulty with that is that we'd need a list of GUIDs and whatnot for every single cosmetic OC in the game in order to support unlocking cosmetics.

the closest we can offer is getting scrip and using that to unlock cosmetics for the current season.

**Pull request merged**
